import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'mr' | 'gu' | 'bn';

const en: Record<string, string> = {
  // Nav
  home: 'Home', about: 'About', services: 'Services', portfolio: 'Portfolio', reviews: 'Reviews', contact: 'Contact',
  login: 'Login', logout: 'Logout', dashboard: 'Dashboard', settings: 'Settings',
  // Dashboard
  welcome: 'Welcome', manage_requests: 'Manage your service requests and track progress',
  total_requests: 'Total Requests', pending: 'Pending', in_progress: 'In Progress', completed: 'Completed',
  new_request: 'New Request', notifications: 'Notifications', no_notifications: 'No new notifications',
  clear_all: 'Clear all', sign_out: 'Sign Out', notification_center: 'Notification Center',
  // Settings
  account_settings: 'Account Settings', profile_info: 'Profile Information', full_name: 'Full Name',
  email: 'Email', phone_number: 'Phone Number', save_changes: 'Save Changes',
  push_notifications: 'Push Notifications', receive_notifications: 'Receive notifications for payments and responses',
  language: 'Language', select_language: 'Select your preferred language',
  preferences: 'Preferences', account_info: 'Account Information', account_id: 'Account ID',
  member_since: 'Member Since', last_sign_in: 'Last Sign In', security: 'Security',
  change_password: 'Change Password', danger_zone: 'Danger Zone',
  back_to_dashboard: 'Back to Dashboard', email_cannot_change: 'Email cannot be changed',
  change_pwd_desc: 'Change your password via email OTP verification',
  sign_out_desc: 'Sign out of your account on this device',
  // Index
  our_services: 'Our Services', services_desc: 'Comprehensive technology solutions tailored to your business needs',
  why_choose_us: 'Why Choose Us', why_desc: "We don't just build products — we build partnerships",
  faq: 'Frequently Asked Questions', faq_desc: 'Everything you need to know before getting started',
  start_project: 'Start Your Project', contact_us: 'Contact Us', view_our_work: 'View Our Work',
  projects_completed: 'Projects Completed', happy_clients: 'Happy Clients', years_experience: 'Years Experience', support: 'Support',
  // Reviews
  what_clients_say: 'What Our Clients Say', share_experience: 'Share Your Experience',
  your_feedback: 'Your feedback helps us grow', sign_in_review: 'Sign in to write a review',
  submit_review: 'Submit Review', screenshots_optional: 'Screenshots (optional, max 3)',
  featured_reviews: 'Featured Client Reviews', featured_reviews_desc: 'Top 10 selected testimonials from our coordinator dashboard',
  click_expand: 'Click to read full review', click_collapse: 'Click to collapse',
  already_reviewed: "You've already submitted a review", already_reviewed_desc: 'Thank you for your feedback! Each user can submit one review.',
  review_submitted: 'Review submitted! ✨', review_submitted_desc: 'Thank you! It will appear after approval.',
  reviews_count: 'Reviews', avg_rating: 'Average Rating',
  real_experiences: 'Real experiences from real clients who trusted Thrylos India',
  // Common
  loading: 'Loading...', error: 'Error', success: 'Success', cancel: 'Cancel', save: 'Save', delete: 'Delete',
  go_back: 'Go Back', processing: 'Processing...', send_message: 'Send Message', sending: 'Sending...',
  // Features
  web_dev: 'Web Development', mobile_apps: 'Mobile Apps', cloud_solutions: 'Cloud Solutions',
  ai_integration: 'AI Integration', cybersecurity: 'Cybersecurity', digital_strategy: 'Digital Strategy',
  web_dev_desc: 'Custom websites and web applications built with modern technologies.',
  mobile_apps_desc: 'Native and cross-platform mobile applications for iOS and Android.',
  cloud_desc: 'Scalable cloud infrastructure and deployment solutions.',
  ai_desc: 'Intelligent automation and AI-powered solutions for your business.',
  cyber_desc: 'Comprehensive security audits and protection services.',
  digital_desc: 'Strategic consulting to transform your digital presence.',
  // Why choose
  fast_delivery: 'Fast Delivery', client_first: 'Client First', on_time_support: 'On-Time Support', availability: '24/7 Availability',
  fast_delivery_desc: 'We deliver projects on time with agile methodology and rapid prototyping.',
  client_first_desc: 'Your vision drives every decision. We build what you need, not what we assume.',
  on_time_desc: 'Dedicated project managers ensure seamless communication throughout.',
  availability_desc: 'Round-the-clock support for critical issues and ongoing maintenance.',
  // Session
  active_sessions: 'Active Sessions', current_device: 'Current Device', connected_accounts: 'Connected Accounts',
  google_account: 'Google Account', not_connected: 'Not connected',
  // About page
  about_title: 'About', about_hero_desc: 'We are a team of passionate technologists dedicated to transforming businesses through innovative digital solutions.',
  our_story: 'Our Story', story_p1: 'Founded with a vision to bridge the gap between innovative technology and business needs, THRYLOS Tech has grown from a small startup to a trusted technology partner for businesses across industries.',
  story_p2: 'Our journey began with a simple belief: technology should empower, not complicate. Today, we continue to uphold this philosophy, delivering solutions that are not just technically excellent but also intuitive and user-friendly.',
  story_p3: 'With a team of experienced developers, designers, and strategists, we\'ve successfully delivered 50+ projects, helping businesses transform their digital presence and streamline their operations.',
  years_excellence: 'Years of Excellence',
  our_values: 'Our Values', values_desc: 'The principles that guide everything we do',
  innovation: 'Innovation', innovation_desc: 'We stay ahead of technology trends to deliver cutting-edge solutions.',
  excellence: 'Excellence', excellence_desc: 'We strive for perfection in every project we undertake.',
  collaboration: 'Collaboration', collaboration_desc: 'We work closely with our clients to understand their unique needs.',
  integrity: 'Integrity', integrity_desc: 'We maintain transparency and honesty in all our dealings.',
  meet_team: 'Meet Our Team', team_desc: 'The talented people behind THRYLOS Tech', team_coming: 'Team members coming soon...',
  // Services page
  services_hero_desc: 'Comprehensive technology solutions tailored to accelerate your business growth',
  no_services: 'No services available at the moment.',
  custom_solution: 'Custom Solution', custom_solution_desc: 'We specialize in creating tailored solutions that perfectly fit your unique business requirements.',
  request_quote: 'Request a Quote',
  // Contact page
  get_in_touch: 'Get in Touch', contact_hero_desc: "Have a project in mind? We'd love to hear from you.",
  lets_connect: "Let's Connect", connect_desc: "Whether you have a question about our services, pricing, or just want to say hello, we're here to help.",
  name: 'Name', phone: 'Phone', subject: 'Subject', message: 'Message',
  your_name: 'Your name', your_email: 'your@email.com', phone_placeholder: '+91 XXX XXX XXXX',
  project_inquiry: 'Project inquiry', tell_us_project: 'Tell us about your project...',
  message_sent: 'Message Sent!', message_sent_desc: "We'll get back to you as soon as possible.",
  // Footer
  privacy_policy: 'Privacy Policy', terms_conditions: 'Terms and Conditions', payment_policy: 'Payment Policy', refund_policy: 'Refund Policy',
  all_rights: 'All rights reserved.',
  // FAQ
  faq_q1: 'How long does a typical project take?',
  faq_a1: 'Project timelines vary based on complexity. A simple website takes 2-4 weeks, while full-stack applications may take 2-3 months. We provide detailed timelines during consultation.',
  faq_q2: 'What technologies do you use?',
  faq_a2: "We use modern stacks including React, Next.js, React Native, Node.js, Python, AWS, and more. We choose the best technology for each project's unique requirements.",
  faq_q3: 'Do you offer post-launch support?',
  faq_a3: 'Yes! We offer comprehensive maintenance and support packages. Every project includes 30 days of free bug-fix support after launch.',
  faq_q4: 'How do payments work?',
  faq_a4: 'We typically work with milestone-based payments. 30% upfront, 40% at midpoint, and 30% on delivery. We accept UPI, bank transfers, and online payments.',
  faq_q5: 'Can I see progress during development?',
  faq_a5: 'Absolutely! You get access to a dedicated dashboard where you can track progress, communicate with your project manager, and review deliverables in real-time.',
  // Get Started
  get_started_title: 'Get Started with', tell_about: 'Tell us about yourself and your project',
  step_of: 'Step', of: 'of',
  personal_info: 'Personal Information', your_name_label: 'Your Name', password: 'Password',
  min_chars: 'Min. 6 characters', company_service: 'Company & Service', company_name: 'Company Name',
  your_company: 'Your company', service_interest: 'What service are you interested in?',
  project_details: 'Project Details', describe_project: 'Describe your project requirements, goals, and timeline...',
  back: 'Back', continue_btn: 'Continue', creating_account: 'Creating Account...', complete_setup: 'Complete Setup',
  welcome_thrylos: 'Welcome to THRYLOS!', account_created: 'Your account has been created successfully.',
  // Verification Plans
  get_verified: 'Get Verified', choose_your: 'Choose Your', plan: 'Plan',
  plans_subtitle: 'Stand out with a verified badge and unlock premium features for your profile',
  plan_basic: 'Basic', plan_pro: 'Pro', per_year: 'year', most_popular: 'MOST POPULAR',
  feature_verified_badge: 'Verified Badge on Profile', feature_profile_highlight: 'Profile Highlight in Search',
  feature_priority_support: 'Priority Support', feature_fast_delivery: 'Fast Project Delivery',
  feature_dedicated_pm: 'Dedicated Project Manager', feature_priority_queue: 'Priority Queue for Requests',
  subscribe_now: 'Subscribe Now', already_subscribed: 'Already Subscribed',
  already_subscribed_desc: 'You already have an active verification subscription.',
  why_get_verified: 'Why Get Verified?',
  trust_credibility: 'Trust & Credibility', trust_desc: 'Verified badge builds trust with other users and clients',
  fast_delivery_plan_desc: 'Pro plan users get priority project delivery',
  stand_out: 'Stand Out', stand_out_desc: 'Your profile appears highlighted in search results',
  priority_support_desc: 'Get faster responses from our support team',
  // Social
  find_people: 'Find People', my_contacts: 'My Contacts', my_profile: 'My Profile',
  search_users: 'Search Users', followers: 'Followers', following: 'Following', follow: 'Follow', unfollow: 'Unfollow',
  projects: 'Projects', no_reviews: 'No reviews yet', edit_profile: 'Edit Profile', view_plans: 'View Plans',
  starting_at: 'Starting at', contact_shared: 'Contact Shared', request_pending: 'Request Pending', get_contact: 'Get Contact',
  // CTA
  cta_desc: "Let's discuss how THRYLOS Tech can help transform your business.",
  write_review: 'Write a Review',
};

const hi: Record<string, string> = {
  home: 'होम', about: 'हमारे बारे में', services: 'सेवाएं', portfolio: 'पोर्टफोलियो', reviews: 'समीक्षाएं', contact: 'संपर्क',
  login: 'लॉगिन', logout: 'लॉगआउट', dashboard: 'डैशबोर्ड', settings: 'सेटिंग्स',
  welcome: 'स्वागत है', manage_requests: 'अपने सेवा अनुरोधों को प्रबंधित करें और प्रगति ट्रैक करें',
  total_requests: 'कुल अनुरोध', pending: 'लंबित', in_progress: 'प्रगति में', completed: 'पूर्ण',
  new_request: 'नया अनुरोध', notifications: 'सूचनाएं', no_notifications: 'कोई नई सूचना नहीं',
  clear_all: 'सभी साफ़ करें', sign_out: 'साइन आउट', notification_center: 'सूचना केंद्र',
  account_settings: 'खाता सेटिंग्स', profile_info: 'प्रोफ़ाइल जानकारी', full_name: 'पूरा नाम',
  email: 'ईमेल', phone_number: 'फ़ोन नंबर', save_changes: 'बदलाव सहेजें',
  push_notifications: 'पुश सूचनाएं', receive_notifications: 'भुगतान और प्रतिक्रियाओं के लिए सूचनाएं प्राप्त करें',
  language: 'भाषा', select_language: 'अपनी पसंदीदा भाषा चुनें',
  preferences: 'प्राथमिकताएं', account_info: 'खाता जानकारी', account_id: 'खाता आईडी',
  member_since: 'सदस्य बने', last_sign_in: 'अंतिम साइन इन', security: 'सुरक्षा',
  change_password: 'पासवर्ड बदलें', danger_zone: 'खतरनाक क्षेत्र',
  back_to_dashboard: 'डैशबोर्ड पर वापस', email_cannot_change: 'ईमेल बदला नहीं जा सकता',
  change_pwd_desc: 'ईमेल OTP सत्यापन के माध्यम से अपना पासवर्ड बदलें',
  sign_out_desc: 'इस डिवाइस पर अपने खाते से साइन आउट करें',
  our_services: 'हमारी सेवाएं', services_desc: 'आपके व्यवसाय की ज़रूरतों के अनुसार व्यापक तकनीकी समाधान',
  why_choose_us: 'हमें क्यों चुनें', why_desc: 'हम सिर्फ उत्पाद नहीं बनाते — हम साझेदारी बनाते हैं',
  faq: 'अक्सर पूछे जाने वाले प्रश्न', faq_desc: 'शुरू करने से पहले आपको जो कुछ जानना चाहिए',
  start_project: 'अपना प्रोजेक्ट शुरू करें', contact_us: 'संपर्क करें', view_our_work: 'हमारा काम देखें',
  projects_completed: 'पूर्ण प्रोजेक्ट', happy_clients: 'खुश ग्राहक', years_experience: 'वर्षों का अनुभव', support: 'सहायता',
  what_clients_say: 'हमारे ग्राहक क्या कहते हैं', share_experience: 'अपना अनुभव साझा करें',
  your_feedback: 'आपकी प्रतिक्रिया हमें बढ़ने में मदद करती है', sign_in_review: 'समीक्षा लिखने के लिए साइन इन करें',
  submit_review: 'समीक्षा सबमिट करें', screenshots_optional: 'स्क्रीनशॉट (वैकल्पिक, अधिकतम 3)',
  featured_reviews: 'चुनिंदा ग्राहक समीक्षाएं', featured_reviews_desc: 'हमारे समन्वयक डैशबोर्ड से शीर्ष 10 चयनित प्रशंसापत्र',
  click_expand: 'पूरी समीक्षा पढ़ने के लिए क्लिक करें', click_collapse: 'छोटा करने के लिए क्लिक करें',
  already_reviewed: 'आपने पहले से ही एक समीक्षा सबमिट की है', already_reviewed_desc: 'आपकी प्रतिक्रिया के लिए धन्यवाद! प्रत्येक उपयोगकर्ता एक समीक्षा सबमिट कर सकता है।',
  review_submitted: 'समीक्षा सबमिट हो गई! ✨', review_submitted_desc: 'धन्यवाद! यह अनुमोदन के बाद दिखाई देगी।',
  reviews_count: 'समीक्षाएं', avg_rating: 'औसत रेटिंग',
  real_experiences: 'थ्रीलॉस इंडिया पर भरोसा करने वाले ग्राहकों के वास्तविक अनुभव',
  loading: 'लोड हो रहा है...', error: 'त्रुटि', success: 'सफल', cancel: 'रद्द करें', save: 'सहेजें', delete: 'हटाएं',
  go_back: 'वापस जाएं', processing: 'प्रक्रिया हो रही है...', send_message: 'संदेश भेजें', sending: 'भेज रहे हैं...',
  web_dev: 'वेब विकास', mobile_apps: 'मोबाइल ऐप्स', cloud_solutions: 'क्लाउड समाधान',
  ai_integration: 'AI एकीकरण', cybersecurity: 'साइबर सुरक्षा', digital_strategy: 'डिजिटल रणनीति',
  web_dev_desc: 'आधुनिक तकनीकों से बनी कस्टम वेबसाइट और वेब ऐप्लिकेशन।',
  mobile_apps_desc: 'iOS और Android के लिए नेटिव और क्रॉस-प्लेटफॉर्म मोबाइल ऐप्लिकेशन।',
  cloud_desc: 'स्केलेबल क्लाउड इंफ्रास्ट्रक्चर और डिप्लॉयमेंट समाधान।',
  ai_desc: 'आपके व्यवसाय के लिए बुद्धिमान ऑटोमेशन और AI-संचालित समाधान।',
  cyber_desc: 'व्यापक सुरक्षा ऑडिट और सुरक्षा सेवाएं।',
  digital_desc: 'आपकी डिजिटल उपस्थिति को बदलने के लिए रणनीतिक परामर्श।',
  fast_delivery: 'तेज़ डिलीवरी', client_first: 'ग्राहक पहले', on_time_support: 'समय पर सहायता', availability: '24/7 उपलब्धता',
  fast_delivery_desc: 'हम एजाइल मेथडोलॉजी और रैपिड प्रोटोटाइपिंग के साथ समय पर प्रोजेक्ट डिलीवर करते हैं।',
  client_first_desc: 'आपकी दृष्टि हर निर्णय को संचालित करती है। हम वही बनाते हैं जो आपको चाहिए।',
  on_time_desc: 'समर्पित प्रोजेक्ट मैनेजर निर्बाध संचार सुनिश्चित करते हैं।',
  availability_desc: 'महत्वपूर्ण मुद्दों और चल रहे रखरखाव के लिए चौबीसों घंटे सहायता।',
  active_sessions: 'सक्रिय सत्र', current_device: 'वर्तमान डिवाइस', connected_accounts: 'जुड़े खाते',
  google_account: 'Google खाता', not_connected: 'जुड़ा नहीं है',
  // About
  about_title: 'हमारे बारे में', about_hero_desc: 'हम प्रौद्योगिकी के शौकीन लोगों की एक टीम हैं जो नवाचार डिजिटल समाधानों के माध्यम से व्यवसायों को बदलने के लिए समर्पित हैं।',
  our_story: 'हमारी कहानी', story_p1: 'नवीन तकनीक और व्यावसायिक जरूरतों के बीच की खाई को पाटने की दृष्टि से स्थापित, THRYLOS Tech एक छोटे स्टार्टअप से उद्योगों के लिए एक विश्वसनीय प्रौद्योगिकी भागीदार बन गया है।',
  story_p2: 'हमारी यात्रा एक सरल विश्वास से शुरू हुई: तकनीक को सशक्त बनाना चाहिए, जटिल नहीं। आज, हम इस दर्शन को बनाए रखते हैं।',
  story_p3: 'अनुभवी डेवलपर्स, डिजाइनरों और रणनीतिकारों की टीम के साथ, हमने 50+ प्रोजेक्ट सफलतापूर्वक पूरे किए हैं।',
  years_excellence: 'उत्कृष्टता के वर्ष',
  our_values: 'हमारे मूल्य', values_desc: 'वे सिद्धांत जो हमारे हर काम का मार्गदर्शन करते हैं',
  innovation: 'नवाचार', innovation_desc: 'हम अत्याधुनिक समाधान देने के लिए तकनीकी रुझानों से आगे रहते हैं।',
  excellence: 'उत्कृष्टता', excellence_desc: 'हम हर प्रोजेक्ट में पूर्णता के लिए प्रयास करते हैं।',
  collaboration: 'सहयोग', collaboration_desc: 'हम अपने ग्राहकों की अनूठी जरूरतों को समझने के लिए उनके साथ मिलकर काम करते हैं।',
  integrity: 'ईमानदारी', integrity_desc: 'हम अपने सभी व्यवहारों में पारदर्शिता और ईमानदारी बनाए रखते हैं।',
  meet_team: 'हमारी टीम से मिलें', team_desc: 'THRYLOS Tech के पीछे प्रतिभाशाली लोग', team_coming: 'टीम सदस्य जल्द आ रहे हैं...',
  // Services
  services_hero_desc: 'आपके व्यवसाय की वृद्धि को तेज करने के लिए व्यापक प्रौद्योगिकी समाधान',
  no_services: 'इस समय कोई सेवा उपलब्ध नहीं है।',
  custom_solution: 'कस्टम समाधान', custom_solution_desc: 'हम आपकी विशिष्ट व्यावसायिक आवश्यकताओं के लिए अनुकूलित समाधान बनाने में माहिर हैं।',
  request_quote: 'कोटेशन का अनुरोध करें',
  // Contact
  get_in_touch: 'संपर्क करें', contact_hero_desc: 'कोई प्रोजेक्ट है? हम आपसे सुनना पसंद करेंगे।',
  lets_connect: 'जुड़ें', connect_desc: 'चाहे आपका कोई सवाल हो या सिर्फ नमस्ते कहना हो, हम यहां मदद के लिए हैं।',
  name: 'नाम', phone: 'फ़ोन', subject: 'विषय', message: 'संदेश',
  your_name: 'आपका नाम', your_email: 'your@email.com', phone_placeholder: '+91 XXX XXX XXXX',
  project_inquiry: 'प्रोजेक्ट पूछताछ', tell_us_project: 'हमें अपने प्रोजेक्ट के बारे में बताएं...',
  message_sent: 'संदेश भेज दिया गया!', message_sent_desc: 'हम जल्द से जल्द आपसे संपर्क करेंगे।',
  // Footer
  privacy_policy: 'गोपनीयता नीति', terms_conditions: 'नियम और शर्तें', payment_policy: 'भुगतान नीति', refund_policy: 'रिफंड नीति',
  all_rights: 'सर्वाधिकार सुरक्षित।',
  // FAQ
  faq_q1: 'एक सामान्य प्रोजेक्ट में कितना समय लगता है?', faq_a1: 'प्रोजेक्ट की समय-सीमा जटिलता पर निर्भर करती है। एक साधारण वेबसाइट 2-4 सप्ताह लेती है, जबकि फुल-स्टैक ऐप्स में 2-3 महीने लग सकते हैं।',
  faq_q2: 'आप कौन सी तकनीकें उपयोग करते हैं?', faq_a2: 'हम React, Next.js, React Native, Node.js, Python, AWS आदि सहित आधुनिक स्टैक का उपयोग करते हैं।',
  faq_q3: 'क्या आप लॉन्च के बाद सहायता प्रदान करते हैं?', faq_a3: 'हाँ! हर प्रोजेक्ट में लॉन्च के बाद 30 दिनों की मुफ्त बग-फिक्स सहायता शामिल है।',
  faq_q4: 'भुगतान कैसे काम करता है?', faq_a4: 'हम मील-पत्थर-आधारित भुगतान करते हैं। 30% अग्रिम, 40% मध्य बिंदु पर, और 30% डिलीवरी पर।',
  faq_q5: 'क्या मैं विकास के दौरान प्रगति देख सकता हूं?', faq_a5: 'बिल्कुल! आपको एक समर्पित डैशबोर्ड मिलता है जहां आप प्रगति ट्रैक कर सकते हैं।',
  // GetStarted
  get_started_title: 'शुरू करें', tell_about: 'अपने बारे में और अपने प्रोजेक्ट के बारे में बताएं',
  step_of: 'चरण', of: 'का',
  personal_info: 'व्यक्तिगत जानकारी', your_name_label: 'आपका नाम', password: 'पासवर्ड',
  min_chars: 'न्यूनतम 6 अक्षर', company_service: 'कंपनी और सेवा', company_name: 'कंपनी का नाम',
  your_company: 'आपकी कंपनी', service_interest: 'आप किस सेवा में रुचि रखते हैं?',
  project_details: 'प्रोजेक्ट विवरण', describe_project: 'अपनी परियोजना आवश्यकताओं, लक्ष्यों और समय-सीमा का वर्णन करें...',
  back: 'वापस', continue_btn: 'जारी रखें', creating_account: 'खाता बना रहे हैं...', complete_setup: 'सेटअप पूरा करें',
  welcome_thrylos: 'THRYLOS में स्वागत है!', account_created: 'आपका खाता सफलतापूर्वक बनाया गया है।',
  // Verification Plans
  get_verified: 'सत्यापित हों', choose_your: 'अपनी', plan: 'योजना चुनें',
  plans_subtitle: 'सत्यापित बैज के साथ अलग दिखें और अपनी प्रोफ़ाइल के लिए प्रीमियम सुविधाएं अनलॉक करें',
  plan_basic: 'बेसिक', plan_pro: 'प्रो', per_year: 'वर्ष', most_popular: 'सबसे लोकप्रिय',
  feature_verified_badge: 'प्रोफ़ाइल पर सत्यापित बैज', feature_profile_highlight: 'खोज में प्रोफ़ाइल हाइलाइट',
  feature_priority_support: 'प्राथमिकता सहायता', feature_fast_delivery: 'तेज़ प्रोजेक्ट डिलीवरी',
  feature_dedicated_pm: 'समर्पित प्रोजेक्ट मैनेजर', feature_priority_queue: 'अनुरोधों के लिए प्राथमिकता कतार',
  subscribe_now: 'अभी सब्सक्राइब करें', already_subscribed: 'पहले से सब्सक्राइब',
  already_subscribed_desc: 'आपके पास पहले से एक सक्रिय सत्यापन सदस्यता है।',
  why_get_verified: 'सत्यापित क्यों हों?',
  trust_credibility: 'विश्वास और विश्वसनीयता', trust_desc: 'सत्यापित बैज अन्य उपयोगकर्ताओं और ग्राहकों के साथ विश्वास बनाता है',
  fast_delivery_plan_desc: 'प्रो प्लान उपयोगकर्ताओं को प्राथमिकता प्रोजेक्ट डिलीवरी मिलती है',
  stand_out: 'अलग दिखें', stand_out_desc: 'खोज परिणामों में आपकी प्रोफ़ाइल हाइलाइट दिखाई देती है',
  priority_support_desc: 'हमारी सहायता टीम से तेज़ प्रतिक्रिया प्राप्त करें',
  find_people: 'लोगों को खोजें', my_contacts: 'मेरे संपर्क', my_profile: 'मेरी प्रोफ़ाइल',
  search_users: 'उपयोगकर्ता खोजें', followers: 'फॉलोअर्स', following: 'फॉलोइंग', follow: 'फ़ॉलो', unfollow: 'अनफ़ॉलो',
  projects: 'प्रोजेक्ट्स', no_reviews: 'अभी तक कोई समीक्षा नहीं', edit_profile: 'प्रोफ़ाइल संपादित करें', view_plans: 'प्लान देखें',
  starting_at: 'शुरू', contact_shared: 'संपर्क साझा', request_pending: 'अनुरोध लंबित', get_contact: 'संपर्क प्राप्त करें',
  cta_desc: 'आइए चर्चा करें कि THRYLOS Tech आपके व्यवसाय को कैसे बदल सकता है।',
  write_review: 'समीक्षा लिखें',
};

const mr: Record<string, string> = {
  home: 'मुख्यपृष्ठ', about: 'आमच्याबद्दल', services: 'सेवा', portfolio: 'पोर्टफोलिओ', reviews: 'पुनरावलोकने', contact: 'संपर्क',
  login: 'लॉगिन', logout: 'लॉगआउट', dashboard: 'डॅशबोर्ड', settings: 'सेटिंग्ज',
  welcome: 'स्वागत आहे', manage_requests: 'तुमच्या सेवा विनंत्या व्यवस्थापित करा',
  total_requests: 'एकूण विनंत्या', pending: 'प्रलंबित', in_progress: 'प्रगतीपथावर', completed: 'पूर्ण',
  new_request: 'नवीन विनंती', notifications: 'सूचना', no_notifications: 'नवीन सूचना नाहीत',
  clear_all: 'सर्व साफ करा', sign_out: 'साइन आउट', notification_center: 'सूचना केंद्र',
  account_settings: 'खाते सेटिंग्ज', profile_info: 'प्रोफाइल माहिती', full_name: 'पूर्ण नाव',
  email: 'ईमेल', phone_number: 'फोन नंबर', save_changes: 'बदल जतन करा',
  push_notifications: 'पुश सूचना', receive_notifications: 'पेमेंट आणि प्रतिसादांसाठी सूचना प्राप्त करा',
  language: 'भाषा', select_language: 'तुमची पसंतीची भाषा निवडा',
  preferences: 'प्राधान्ये', account_info: 'खाते माहिती', account_id: 'खाते आयडी',
  member_since: 'सदस्य', last_sign_in: 'शेवटचा साइन इन', security: 'सुरक्षा',
  change_password: 'पासवर्ड बदला', danger_zone: 'धोकादायक क्षेत्र',
  back_to_dashboard: 'डॅशबोर्डवर परत', email_cannot_change: 'ईमेल बदलता येत नाही',
  change_pwd_desc: 'ईमेल OTP सत्यापनाद्वारे तुमचा पासवर्ड बदला',
  sign_out_desc: 'या डिव्हाइसवर तुमच्या खात्यातून साइन आउट करा',
  our_services: 'आमच्या सेवा', services_desc: 'तुमच्या व्यवसायाच्या गरजांनुसार सर्वसमावेशक तंत्रज्ञान उपाय',
  why_choose_us: 'आम्हाला का निवडावे', why_desc: 'आम्ही फक्त उत्पादने बनवत नाही — आम्ही भागीदारी बनवतो',
  faq: 'वारंवार विचारले जाणारे प्रश्न', faq_desc: 'सुरू करण्यापूर्वी तुम्हाला जे माहित असणे आवश्यक आहे',
  start_project: 'तुमचा प्रकल्प सुरू करा', contact_us: 'संपर्क करा', view_our_work: 'आमचे काम पहा',
  projects_completed: 'पूर्ण प्रकल्प', happy_clients: 'आनंदी ग्राहक', years_experience: 'वर्षांचा अनुभव', support: 'सहाय्य',
  what_clients_say: 'आमचे ग्राहक काय म्हणतात', share_experience: 'तुमचा अनुभव शेअर करा',
  your_feedback: 'तुमचा अभिप्राय आम्हाला वाढण्यास मदत करतो', sign_in_review: 'पुनरावलोकन लिहिण्यासाठी साइन इन करा',
  submit_review: 'पुनरावलोकन सबमिट करा', screenshots_optional: 'स्क्रीनशॉट (पर्यायी, कमाल 3)',
  featured_reviews: 'वैशिष्ट्यीकृत ग्राहक पुनरावलोकने', featured_reviews_desc: 'आमच्या समन्वयक डॅशबोर्डवरील शीर्ष 10 निवडक प्रशंसापत्रे',
  click_expand: 'पूर्ण पुनरावलोकन वाचण्यासाठी क्लिक करा', click_collapse: 'लहान करण्यासाठी क्लिक करा',
  already_reviewed: 'तुम्ही आधीच एक पुनरावलोकन सबमिट केले आहे', already_reviewed_desc: 'तुमच्या अभिप्रायाबद्दल धन्यवाद!',
  review_submitted: 'पुनरावलोकन सबमिट झाले! ✨', review_submitted_desc: 'धन्यवाद! ते मंजुरीनंतर दिसेल.',
  reviews_count: 'पुनरावलोकने', avg_rating: 'सरासरी रेटिंग',
  real_experiences: 'थ्रीलॉस इंडियावर विश्वास ठेवणाऱ्या ग्राहकांचे वास्तविक अनुभव',
  loading: 'लोड होत आहे...', error: 'त्रुटी', success: 'यशस्वी', cancel: 'रद्द करा', save: 'जतन करा', delete: 'हटवा',
  go_back: 'मागे जा', processing: 'प्रक्रिया होत आहे...', send_message: 'संदेश पाठवा', sending: 'पाठवत आहे...',
  web_dev: 'वेब विकास', mobile_apps: 'मोबाइल ॲप्स', cloud_solutions: 'क्लाउड उपाय',
  ai_integration: 'AI एकत्रीकरण', cybersecurity: 'सायबर सुरक्षा', digital_strategy: 'डिजिटल रणनीती',
  web_dev_desc: 'आधुनिक तंत्रज्ञानाने तयार केलेल्या कस्टम वेबसाइट्स.', mobile_apps_desc: 'iOS आणि Android साठी मोबाइल ॲप्स.',
  cloud_desc: 'स्केलेबल क्लाउड पायाभूत सुविधा.', ai_desc: 'AI-संचालित उपाय.',
  cyber_desc: 'सर्वसमावेशक सुरक्षा ऑडिट.', digital_desc: 'डिजिटल उपस्थिती बदलण्यासाठी रणनीतिक सल्ला.',
  fast_delivery: 'वेगवान डिलिव्हरी', client_first: 'ग्राहक प्रथम', on_time_support: 'वेळेवर सहाय्य', availability: '24/7 उपलब्धता',
  fast_delivery_desc: 'वेळेवर प्रकल्प डिलिव्हर करतो.', client_first_desc: 'तुमची दृष्टी प्रत्येक निर्णय चालवते.',
  on_time_desc: 'समर्पित प्रकल्प व्यवस्थापक.', availability_desc: 'चोवीस तास सहाय्य.',
  active_sessions: 'सक्रिय सत्रे', current_device: 'सध्याचे डिव्हाइस', connected_accounts: 'जोडलेली खाती',
  google_account: 'Google खाते', not_connected: 'जोडलेले नाही',
  about_title: 'आमच्याबद्दल', about_hero_desc: 'नवोन्मेषी डिजिटल उपायांद्वारे व्यवसाय बदलण्यासाठी समर्पित तंत्रज्ञ.',
  our_story: 'आमची कथा', story_p1: 'THRYLOS Tech एका लहान स्टार्टअपमधून विश्वसनीय तंत्रज्ञान भागीदार बनले आहे.',
  story_p2: 'तंत्रज्ञानाने सक्षम केले पाहिजे, गुंतागुंत नाही.', story_p3: '50+ प्रकल्प यशस्वीरीत्या पूर्ण.',
  years_excellence: 'उत्कृष्टतेची वर्षे',
  our_values: 'आमची मूल्ये', values_desc: 'आम्ही जे करतो त्याचे मार्गदर्शन करणारी तत्त्वे',
  innovation: 'नवकल्पना', innovation_desc: 'अत्याधुनिक उपाय.',
  excellence: 'उत्कृष्टता', excellence_desc: 'प्रत्येक प्रकल्पात परिपूर्णता.',
  collaboration: 'सहकार्य', collaboration_desc: 'ग्राहकांसोबत जवळून काम.',
  integrity: 'प्रामाणिकता', integrity_desc: 'पारदर्शकता आणि प्रामाणिकपणा.',
  meet_team: 'आमच्या टीमला भेटा', team_desc: 'THRYLOS Tech मागील प्रतिभावान लोक', team_coming: 'टीम सदस्य लवकरच...',
  services_hero_desc: 'व्यवसाय वाढीसाठी सर्वसमावेशक तंत्रज्ञान उपाय',
  no_services: 'सध्या कोणत्याही सेवा उपलब्ध नाहीत.',
  custom_solution: 'कस्टम उपाय', custom_solution_desc: 'तुमच्या आवश्यकतांनुसार अनुकूलित उपाय.',
  request_quote: 'कोटेशन विनंती',
  get_in_touch: 'संपर्क साधा', contact_hero_desc: 'प्रकल्प आहे? आम्हाला ऐकायला आवडेल.',
  lets_connect: 'जोडा', connect_desc: 'कोणताही प्रश्न असो, आम्ही मदतीसाठी येथे आहोत.',
  name: 'नाव', phone: 'फोन', subject: 'विषय', message: 'संदेश',
  your_name: 'तुमचे नाव', your_email: 'your@email.com', phone_placeholder: '+91 XXX XXX XXXX',
  project_inquiry: 'प्रकल्प चौकशी', tell_us_project: 'तुमच्या प्रकल्पाबद्दल सांगा...',
  message_sent: 'संदेश पाठवला!', message_sent_desc: 'आम्ही लवकरच संपर्क करू.',
  privacy_policy: 'गोपनीयता धोरण', terms_conditions: 'अटी आणि शर्ती', payment_policy: 'पेमेंट धोरण', refund_policy: 'रिफंड धोरण',
  all_rights: 'सर्व हक्क राखीव.',
  faq_q1: 'एक सामान्य प्रकल्प किती वेळ घेतो?', faq_a1: 'साधी वेबसाइट 2-4 आठवडे, फुल-स्टॅक ॲप 2-3 महिने.',
  faq_q2: 'तुम्ही कोणते तंत्रज्ञान वापरता?', faq_a2: 'React, Next.js, Node.js, Python, AWS इत्यादी.',
  faq_q3: 'लॉन्चनंतर सहाय्य मिळते का?', faq_a3: 'होय! 30 दिवसांचे मोफत बग-फिक्स सहाय्य.',
  faq_q4: 'पेमेंट कसे काम करते?', faq_a4: 'मैलस्टोन-आधारित पेमेंट. 30% आगाऊ, 40% मध्यभागी, 30% डिलिव्हरीवर.',
  faq_q5: 'विकासादरम्यान प्रगती पाहता येते का?', faq_a5: 'नक्कीच! तुम्हाला समर्पित डॅशबोर्ड मिळतो.',
  get_started_title: 'सुरू करा', tell_about: 'स्वतःबद्दल आणि प्रकल्पाबद्दल सांगा',
  step_of: 'चरण', of: 'चा', personal_info: 'वैयक्तिक माहिती', your_name_label: 'तुमचे नाव', password: 'पासवर्ड',
  min_chars: 'किमान 6 अक्षरे', company_service: 'कंपनी आणि सेवा', company_name: 'कंपनीचे नाव',
  your_company: 'तुमची कंपनी', service_interest: 'तुम्हाला कोणत्या सेवेत रस आहे?',
  project_details: 'प्रकल्प तपशील', describe_project: 'तुमच्या प्रकल्पाच्या आवश्यकतांचे वर्णन करा...',
  back: 'मागे', continue_btn: 'पुढे', creating_account: 'खाते तयार करत आहोत...', complete_setup: 'सेटअप पूर्ण करा',
  welcome_thrylos: 'THRYLOS मध्ये स्वागत!', account_created: 'तुमचे खाते यशस्वीरीत्या तयार झाले.',
  get_verified: 'सत्यापित व्हा', choose_your: 'तुमची', plan: 'योजना निवडा',
  plans_subtitle: 'सत्यापित बॅजसह वेगळे दिसा आणि प्रीमियम वैशिष्ट्ये अनलॉक करा',
  plan_basic: 'बेसिक', plan_pro: 'प्रो', per_year: 'वर्ष', most_popular: 'सर्वात लोकप्रिय',
  feature_verified_badge: 'प्रोफाइलवर सत्यापित बॅज', feature_profile_highlight: 'शोधात प्रोफाइल हायलाइट',
  feature_priority_support: 'प्राधान्य सहाय्य', feature_fast_delivery: 'जलद प्रकल्प डिलिव्हरी',
  feature_dedicated_pm: 'समर्पित प्रकल्प व्यवस्थापक', feature_priority_queue: 'विनंत्यांसाठी प्राधान्य रांग',
  subscribe_now: 'आता सबस्क्राइब करा', already_subscribed: 'आधीच सबस्क्राइब',
  already_subscribed_desc: 'तुमच्याकडे आधीच सक्रिय सत्यापन सदस्यता आहे.',
  why_get_verified: 'सत्यापित का व्हावे?',
  trust_credibility: 'विश्वास आणि विश्वासार्हता', trust_desc: 'सत्यापित बॅज विश्वास निर्माण करतो',
  fast_delivery_plan_desc: 'प्रो प्लॅन वापरकर्त्यांना प्राधान्य डिलिव्हरी मिळते',
  stand_out: 'वेगळे दिसा', stand_out_desc: 'शोध परिणामांमध्ये प्रोफाइल हायलाइट दिसते',
  priority_support_desc: 'सहाय्य टीमकडून जलद प्रतिसाद',
  find_people: 'लोक शोधा', my_contacts: 'माझे संपर्क', my_profile: 'माझी प्रोफाइल',
  search_users: 'वापरकर्ते शोधा', followers: 'अनुयायी', following: 'अनुसरण', follow: 'अनुसरण करा', unfollow: 'अनुसरण थांबवा',
  projects: 'प्रकल्प', no_reviews: 'अजून कोणतीही पुनरावलोकने नाहीत', edit_profile: 'प्रोफाइल संपादित करा', view_plans: 'प्लॅन पहा',
  starting_at: 'पासून', contact_shared: 'संपर्क सामायिक', request_pending: 'विनंती प्रलंबित', get_contact: 'संपर्क मिळवा',
  cta_desc: 'THRYLOS Tech तुमच्या व्यवसायाला कसे बदलू शकते याची चर्चा करूया.',
  write_review: 'पुनरावलोकन लिहा',
};

const gu: Record<string, string> = {
  home: 'હોમ', about: 'અમારા વિશે', services: 'સેવાઓ', portfolio: 'પોર્ટફોલિયો', reviews: 'સમીક્ષાઓ', contact: 'સંપર્ક',
  login: 'લૉગિન', logout: 'લૉગઆઉટ', dashboard: 'ડેશબોર્ડ', settings: 'સેટિંગ્સ',
  welcome: 'સ્વાગત છે', manage_requests: 'તમારી સેવા વિનંતીઓ મેનેજ કરો',
  total_requests: 'કુલ વિનંતીઓ', pending: 'બાકી', in_progress: 'પ્રગતિમાં', completed: 'પૂર્ણ',
  new_request: 'નવી વિનંતી', notifications: 'સૂચનાઓ', no_notifications: 'કોઈ નવી સૂચનાઓ નથી',
  clear_all: 'બધા સાફ કરો', sign_out: 'સાઇન આઉટ', notification_center: 'સૂચના કેન્દ્ર',
  account_settings: 'એકાઉન્ટ સેટિંગ્સ', profile_info: 'પ્રોફાઇલ માહિતી', full_name: 'પૂર્ણ નામ',
  email: 'ઇમેઇલ', phone_number: 'ફોન નંબર', save_changes: 'ફેરફારો સાચવો',
  push_notifications: 'પુશ સૂચનાઓ', receive_notifications: 'ચુકવણી અને પ્રતિસાદ માટે સૂચનાઓ મેળવો',
  language: 'ભાષા', select_language: 'તમારી પસંદીદા ભાષા પસંદ કરો',
  preferences: 'પસંદગીઓ', account_info: 'એકાઉન્ટ માહિતી', account_id: 'એકાઉન્ટ ID',
  member_since: 'સભ્ય', last_sign_in: 'છેલ્લો સાઇન ઇન', security: 'સુરક્ષા',
  change_password: 'પાસવર્ડ બદલો', danger_zone: 'ખતરનાક ઝોન',
  back_to_dashboard: 'ડેશબોર્ડ પર પાછા', email_cannot_change: 'ઇમેઇલ બદલી શકાતો નથી',
  change_pwd_desc: 'ઇમેઇલ OTP ચકાસણી દ્વારા તમારો પાસવર્ડ બદલો',
  sign_out_desc: 'આ ઉપકરણ પર તમારા ખાતામાંથી સાઇન આઉટ કરો',
  our_services: 'અમારી સેવાઓ', services_desc: 'તમારા વ્યવસાયની જરૂરિયાતો અનુસાર વ્યાપક ટેકનોલોજી ઉકેલો',
  why_choose_us: 'અમને શા માટે પસંદ કરો', why_desc: 'અમે માત્ર ઉત્પાદનો નથી બનાવતા — અમે ભાગીદારી બનાવીએ છીએ',
  faq: 'વારંવાર પૂછાતા પ્રશ્નો', faq_desc: 'શરૂ કરતા પહેલા તમારે જે જાણવાની જરૂર છે',
  start_project: 'તમારો પ્રોજેક્ટ શરૂ કરો', contact_us: 'સંપર્ક કરો', view_our_work: 'અમારું કાર્ય જુઓ',
  projects_completed: 'પૂર્ણ પ્રોજેક્ટ', happy_clients: 'ખુશ ગ્રાહકો', years_experience: 'વર્ષોનો અનુભવ', support: 'સહાય',
  what_clients_say: 'અમારા ગ્રાહકો શું કહે છે', share_experience: 'તમારો અનુભવ શેર કરો',
  your_feedback: 'તમારો પ્રતિસાદ અમને વધવામાં મદદ કરે છે', sign_in_review: 'સમીક્ષા લખવા માટે સાઇન ઇન કરો',
  submit_review: 'સમીક્ષા સબમિટ કરો', screenshots_optional: 'સ્ક્રીનશૉટ (વૈકલ્પિક, મહત્તમ 3)',
  featured_reviews: 'વિશેષ ગ્રાહક સમીક્ષાઓ', featured_reviews_desc: 'અમારા સમન્વયક ડેશબોર્ડમાંથી ટોચના 10 પસંદ કરેલા પ્રમાણપત્રો',
  click_expand: 'પૂર્ણ સમીક્ષા વાંચવા ક્લિક કરો', click_collapse: 'નાનું કરવા ક્લિક કરો',
  already_reviewed: 'તમે પહેલેથી જ સમીક્ષા સબમિટ કરી છે', already_reviewed_desc: 'તમારા પ્રતિસાદ માટે આભાર!',
  review_submitted: 'સમીક્ષા સબમિટ થઈ! ✨', review_submitted_desc: 'આભાર! તે મંજૂરી પછી દેખાશે.',
  reviews_count: 'સમીક્ષાઓ', avg_rating: 'સરેરાશ રેટિંગ',
  real_experiences: 'થ્રીલૉસ ઇન્ડિયા પર વિશ્વાસ કરનારા ગ્રાહકોના વાસ્તવિક અનુભવો',
  loading: 'લોડ થઈ રહ્યું છે...', error: 'ભૂલ', success: 'સફળ', cancel: 'રદ કરો', save: 'સાચવો', delete: 'કાઢી નાખો',
  go_back: 'પાછા જાઓ', processing: 'પ્રક્રિયા થઈ રહી છે...', send_message: 'સંદેશ મોકલો', sending: 'મોકલી રહ્યા છીએ...',
  web_dev: 'વેબ ડેવલપમેન્ટ', mobile_apps: 'મોબાઇલ એપ્સ', cloud_solutions: 'ક્લાઉડ ઉકેલો',
  ai_integration: 'AI ઇન્ટિગ્રેશન', cybersecurity: 'સાયબર સુરક્ષા', digital_strategy: 'ડિજિટલ વ્યૂહરચના',
  web_dev_desc: 'આધુનિક ટેકનોલોજીથી બનેલ કસ્ટમ વેબસાઇટ.', mobile_apps_desc: 'iOS અને Android માટે મોબાઇલ એપ્સ.',
  cloud_desc: 'સ્કેલેબલ ક્લાઉડ ઇન્ફ્રાસ્ટ્રક્ચર.', ai_desc: 'AI-સંચાલિત ઉકેલો.',
  cyber_desc: 'વ્યાપક સુરક્ષા ઓડિટ.', digital_desc: 'ડિજિટલ હાજરી બદલવા માટે વ્યૂહાત્મક પરામર્શ.',
  fast_delivery: 'ઝડપી ડિલિવરી', client_first: 'ગ્રાહક પ્રથમ', on_time_support: 'સમયસર સહાય', availability: '24/7 ઉપલબ્ધતા',
  fast_delivery_desc: 'સમયસર પ્રોજેક્ટ ડિલિવર કરીએ છીએ.', client_first_desc: 'તમારું વિઝન દરેક નિર્ણયને ચલાવે છે.',
  on_time_desc: 'સમર્પિત પ્રોજેક્ટ મેનેજર્સ.', availability_desc: 'ચોવીસ કલાક સહાય.',
  active_sessions: 'સક્રિય સત્રો', current_device: 'વર્તમાન ઉપકરણ', connected_accounts: 'જોડાયેલા ખાતાં',
  google_account: 'Google ખાતું', not_connected: 'જોડાયેલ નથી',
  about_title: 'અમારા વિશે', about_hero_desc: 'નવીન ડિજિટલ ઉકેલો દ્વારા વ્યવસાયો બદલવા માટે સમર્પિત.',
  our_story: 'અમારી વાર્તા', story_p1: 'THRYLOS Tech નાના સ્ટાર્ટઅપમાંથી વિશ્વસનીય ટેકનોલોજી ભાગીદાર બન્યું.',
  story_p2: 'ટેકનોલોજી સશક્ત બનાવવી જોઈએ, ગૂંચવણભરી નહીં.', story_p3: '50+ પ્રોજેક્ટ સફળતાપૂર્વક પૂર્ણ.',
  years_excellence: 'ઉત્કૃષ્ટતાના વર્ષો',
  our_values: 'અમારા મૂલ્યો', values_desc: 'અમે જે કરીએ છીએ તેનું માર્ગદર્શન કરતા સિદ્ધાંતો',
  innovation: 'નવીનતા', innovation_desc: 'અત્યાધુનિક ઉકેલો.',
  excellence: 'ઉત્કૃષ્ટતા', excellence_desc: 'દરેક પ્રોજેક્ટમાં પૂર્ણતા.',
  collaboration: 'સહકાર', collaboration_desc: 'ગ્રાહકો સાથે નજીકથી કામ.',
  integrity: 'પ્રામાણિકતા', integrity_desc: 'પારદર્શિતા અને પ્રામાણિકતા.',
  meet_team: 'અમારી ટીમને મળો', team_desc: 'THRYLOS Tech પાછળના પ્રતિભાશાળી લોકો', team_coming: 'ટીમ સભ્યો ટૂંક સમયમાં...',
  services_hero_desc: 'વ્યવસાય વૃદ્ધિ માટે વ્યાપક ટેકનોલોજી ઉકેલો',
  no_services: 'હાલમાં કોઈ સેવાઓ ઉપલબ્ધ નથી.',
  custom_solution: 'કસ્ટમ ઉકેલ', custom_solution_desc: 'તમારી આવશ્યકતાઓ માટે અનુકૂળ ઉકેલો.',
  request_quote: 'કોટેશન વિનંતી',
  get_in_touch: 'સંપર્ક કરો', contact_hero_desc: 'પ્રોજેક્ટ છે? અમે તમારી પાસેથી સાંભળવાનું પસંદ કરીશું.',
  lets_connect: 'જોડાઓ', connect_desc: 'કોઈપણ પ્રશ્ન હોય, અમે અહીં મદદ માટે છીએ.',
  name: 'નામ', phone: 'ફોન', subject: 'વિષય', message: 'સંદેશ',
  your_name: 'તમારું નામ', your_email: 'your@email.com', phone_placeholder: '+91 XXX XXX XXXX',
  project_inquiry: 'પ્રોજેક્ટ પૂછપરછ', tell_us_project: 'તમારા પ્રોજેક્ટ વિશે જણાવો...',
  message_sent: 'સંદેશ મોકલ્યો!', message_sent_desc: 'અમે ટૂંક સમયમાં સંપર્ક કરીશું.',
  privacy_policy: 'ગોપનીયતા નીતિ', terms_conditions: 'નિયમો અને શરતો', payment_policy: 'ચુકવણી નીતિ', refund_policy: 'રિફંડ નીતિ',
  all_rights: 'બધા હકો અનામત.',
  faq_q1: 'સામાન્ય પ્રોજેક્ટ કેટલો સમય લે છે?', faq_a1: 'સાદી વેબસાઇટ 2-4 અઠવાડિયા, ફુલ-સ્ટેક એપ 2-3 મહિના.',
  faq_q2: 'તમે કઈ ટેકનોલોજી વાપરો છો?', faq_a2: 'React, Next.js, Node.js, Python, AWS વગેરે.',
  faq_q3: 'લોન્ચ પછી સહાય મળે છે?', faq_a3: 'હા! 30 દિવસનું મફત બગ-ફિક્સ સહાય.',
  faq_q4: 'ચુકવણી કેવી રીતે થાય છે?', faq_a4: 'માઇલસ્ટોન-આધારિત ચુકવણી. 30% અગાઉથી, 40% મધ્ય, 30% ડિલિવરી.',
  faq_q5: 'વિકાસ દરમિયાન પ્રગતિ જોઈ શકાય?', faq_a5: 'ચોક્કસ! તમને સમર્પિત ડેશબોર્ડ મળે છે.',
  get_started_title: 'શરૂ કરો', tell_about: 'તમારા વિશે અને પ્રોજેક્ટ વિશે જણાવો',
  step_of: 'પગલું', of: 'નું', personal_info: 'વ્યક્તિગત માહિતી', your_name_label: 'તમારું નામ', password: 'પાસવર્ડ',
  min_chars: 'ઓછામાં ઓછા 6 અક્ષરો', company_service: 'કંપની અને સેવા', company_name: 'કંપનીનું નામ',
  your_company: 'તમારી કંપની', service_interest: 'તમને કઈ સેવામાં રસ છે?',
  project_details: 'પ્રોજેક્ટ વિગતો', describe_project: 'તમારી પ્રોજેક્ટ જરૂરિયાતોનું વર્ણન કરો...',
  back: 'પાછા', continue_btn: 'ચાલુ રાખો', creating_account: 'ખાતું બનાવી રહ્યાં છીએ...', complete_setup: 'સેટઅપ પૂર્ણ કરો',
  welcome_thrylos: 'THRYLOS માં સ્વાગત!', account_created: 'તમારું ખાતું સફળતાપૂર્વક બનાવવામાં આવ્યું.',
  get_verified: 'ચકાસાયેલ થાઓ', choose_your: 'તમારી', plan: 'યોજના પસંદ કરો',
  plans_subtitle: 'ચકાસાયેલ બેજ સાથે અલગ તરી આવો અને પ્રીમિયમ સુવિધાઓ અનલૉક કરો',
  plan_basic: 'બેસિક', plan_pro: 'પ્રો', per_year: 'વર્ષ', most_popular: 'સૌથી લોકપ્રિય',
  feature_verified_badge: 'પ્રોફાઇલ પર ચકાસાયેલ બેજ', feature_profile_highlight: 'શોધમાં પ્રોફાઇલ હાઇલાઇટ',
  feature_priority_support: 'પ્રાધાન્ય સહાય', feature_fast_delivery: 'ઝડપી પ્રોજેક્ટ ડિલિવરી',
  feature_dedicated_pm: 'સમર્પિત પ્રોજેક્ટ મેનેજર', feature_priority_queue: 'વિનંતીઓ માટે પ્રાધાન્ય કતાર',
  subscribe_now: 'હમણાં સબસ્ક્રાઇબ કરો', already_subscribed: 'પહેલેથી સબસ્ક્રાઇબ',
  already_subscribed_desc: 'તમારી પાસે પહેલેથી સક્રિય ચકાસણી સબસ્ક્રિપ્શન છે.',
  why_get_verified: 'ચકાસાયેલ કેમ થવું?',
  trust_credibility: 'વિશ્વાસ અને વિશ્વસનીયતા', trust_desc: 'ચકાસાયેલ બેજ વિશ્વાસ બનાવે છે',
  fast_delivery_plan_desc: 'પ્રો પ્લાન વપરાશકર્તાઓને પ્રાધાન્ય ડિલિવરી',
  stand_out: 'અલગ તરી આવો', stand_out_desc: 'શોધ પરિણામોમાં પ્રોફાઇલ હાઇલાઇટ',
  priority_support_desc: 'સહાય ટીમ પાસેથી ઝડપી પ્રતિસાદ',
  find_people: 'લોકો શોધો', my_contacts: 'મારા સંપર્કો', my_profile: 'મારી પ્રોફાઇલ',
  search_users: 'વપરાશકર્તાઓ શોધો', followers: 'અનુયાયીઓ', following: 'અનુસરી રહ્યા છે', follow: 'અનુસરો', unfollow: 'અનફૉલો',
  projects: 'પ્રોજેક્ટ', no_reviews: 'હજુ કોઈ સમીક્ષાઓ નથી', edit_profile: 'પ્રોફાઇલ સંપાદિત કરો', view_plans: 'પ્લાન જુઓ',
  starting_at: 'થી શરૂ', contact_shared: 'સંપર્ક શેર', request_pending: 'વિનંતી બાકી', get_contact: 'સંપર્ક મેળવો',
  cta_desc: 'ચાલો ચર્ચા કરીએ કે THRYLOS Tech તમારા વ્યવસાયને કેવી રીતે બદલી શકે.',
  write_review: 'સમીક્ષા લખો',
};

const bn: Record<string, string> = {
  home: 'হোম', about: 'আমাদের সম্পর্কে', services: 'সেবা', portfolio: 'পোর্টফোলিও', reviews: 'পর্যালোচনা', contact: 'যোগাযোগ',
  login: 'লগইন', logout: 'লগআউট', dashboard: 'ড্যাশবোর্ড', settings: 'সেটিংস',
  welcome: 'স্বাগতম', manage_requests: 'আপনার সেবা অনুরোধগুলি পরিচালনা করুন',
  total_requests: 'মোট অনুরোধ', pending: 'অপেক্ষমান', in_progress: 'চলমান', completed: 'সম্পন্ন',
  new_request: 'নতুন অনুরোধ', notifications: 'বিজ্ঞপ্তি', no_notifications: 'কোনো নতুন বিজ্ঞপ্তি নেই',
  clear_all: 'সব মুছুন', sign_out: 'সাইন আউট', notification_center: 'বিজ্ঞপ্তি কেন্দ্র',
  account_settings: 'অ্যাকাউন্ট সেটিংস', profile_info: 'প্রোফাইল তথ্য', full_name: 'পূর্ণ নাম',
  email: 'ইমেইল', phone_number: 'ফোন নম্বর', save_changes: 'পরিবর্তন সংরক্ষণ করুন',
  push_notifications: 'পুশ বিজ্ঞপ্তি', receive_notifications: 'পেমেন্ট এবং প্রতিক্রিয়ার জন্য বিজ্ঞপ্তি পান',
  language: 'ভাষা', select_language: 'আপনার পছন্দের ভাষা নির্বাচন করুন',
  preferences: 'পছন্দসমূহ', account_info: 'অ্যাকাউন্ট তথ্য', account_id: 'অ্যাকাউন্ট ID',
  member_since: 'সদস্য', last_sign_in: 'শেষ সাইন ইন', security: 'নিরাপত্তা',
  change_password: 'পাসওয়ার্ড পরিবর্তন', danger_zone: 'বিপদ অঞ্চল',
  back_to_dashboard: 'ড্যাশবোর্ডে ফিরুন', email_cannot_change: 'ইমেইল পরিবর্তন করা যায় না',
  change_pwd_desc: 'ইমেইল OTP যাচাইয়ের মাধ্যমে পাসওয়ার্ড পরিবর্তন করুন',
  sign_out_desc: 'এই ডিভাইসে আপনার অ্যাকাউন্ট থেকে সাইন আউট করুন',
  our_services: 'আমাদের সেবা', services_desc: 'আপনার ব্যবসায়ের চাহিদা অনুযায়ী ব্যাপক প্রযুক্তি সমাধান',
  why_choose_us: 'কেন আমাদের বেছে নেবেন', why_desc: 'আমরা শুধু পণ্য তৈরি করি না — আমরা অংশীদারিত্ব তৈরি করি',
  faq: 'সচরাচর জিজ্ঞাসিত প্রশ্ন', faq_desc: 'শুরু করার আগে আপনার যা জানা দরকার',
  start_project: 'আপনার প্রকল্প শুরু করুন', contact_us: 'যোগাযোগ করুন', view_our_work: 'আমাদের কাজ দেখুন',
  projects_completed: 'সম্পন্ন প্রকল্প', happy_clients: 'খুশি ক্লায়েন্ট', years_experience: 'বছরের অভিজ্ঞতা', support: 'সহায়তা',
  what_clients_say: 'আমাদের ক্লায়েন্টরা কী বলেন', share_experience: 'আপনার অভিজ্ঞতা শেয়ার করুন',
  your_feedback: 'আপনার মতামত আমাদের বাড়তে সাহায্য করে', sign_in_review: 'পর্যালোচনা লিখতে সাইন ইন করুন',
  submit_review: 'পর্যালোচনা জমা দিন', screenshots_optional: 'স্ক্রিনশট (ঐচ্ছিক, সর্বাধিক ৩)',
  featured_reviews: 'বৈশিষ্ট্যযুক্ত ক্লায়েন্ট পর্যালোচনা', featured_reviews_desc: 'আমাদের সমন্বয়কারী ড্যাশবোর্ড থেকে শীর্ষ ১০টি নির্বাচিত প্রশংসাপত্র',
  click_expand: 'পূর্ণ পর্যালোচনা পড়তে ক্লিক করুন', click_collapse: 'ছোট করতে ক্লিক করুন',
  already_reviewed: 'আপনি ইতিমধ্যে একটি পর্যালোচনা জমা দিয়েছেন', already_reviewed_desc: 'আপনার মতামতের জন্য ধন্যবাদ!',
  review_submitted: 'পর্যালোচনা জমা হয়েছে! ✨', review_submitted_desc: 'ধন্যবাদ! এটি অনুমোদনের পরে দেখা যাবে।',
  reviews_count: 'পর্যালোচনা', avg_rating: 'গড় রেটিং',
  real_experiences: 'থ্রীলস ইন্ডিয়ায় বিশ্বাসকারী ক্লায়েন্টদের বাস্তব অভিজ্ঞতা',
  loading: 'লোড হচ্ছে...', error: 'ত্রুটি', success: 'সফল', cancel: 'বাতিল', save: 'সংরক্ষণ', delete: 'মুছুন',
  go_back: 'ফিরে যান', processing: 'প্রক্রিয়াকরণ হচ্ছে...', send_message: 'বার্তা পাঠান', sending: 'পাঠানো হচ্ছে...',
  web_dev: 'ওয়েব ডেভেলপমেন্ট', mobile_apps: 'মোবাইল অ্যাপ', cloud_solutions: 'ক্লাউড সমাধান',
  ai_integration: 'AI ইন্টিগ্রেশন', cybersecurity: 'সাইবার নিরাপত্তা', digital_strategy: 'ডিজিটাল কৌশল',
  web_dev_desc: 'আধুনিক প্রযুক্তি দিয়ে তৈরি কাস্টম ওয়েবসাইট।', mobile_apps_desc: 'iOS ও Android-এর জন্য মোবাইল অ্যাপ।',
  cloud_desc: 'স্কেলেবল ক্লাউড অবকাঠামো।', ai_desc: 'AI-চালিত সমাধান।',
  cyber_desc: 'ব্যাপক নিরাপত্তা অডিট।', digital_desc: 'ডিজিটাল উপস্থিতি রূপান্তর করতে কৌশলগত পরামর্শ।',
  fast_delivery: 'দ্রুত ডেলিভারি', client_first: 'ক্লায়েন্ট প্রথম', on_time_support: 'সময়মত সহায়তা', availability: '24/7 উপলব্ধতা',
  fast_delivery_desc: 'সময়মত প্রকল্প ডেলিভার করি।', client_first_desc: 'আপনার দৃষ্টিভঙ্গি প্রতিটি সিদ্ধান্ত চালায়।',
  on_time_desc: 'নিবেদিত প্রকল্প ব্যবস্থাপক।', availability_desc: 'চব্বিশ ঘণ্টা সহায়তা।',
  active_sessions: 'সক্রিয় সেশন', current_device: 'বর্তমান ডিভাইস', connected_accounts: 'সংযুক্ত অ্যাকাউন্ট',
  google_account: 'Google অ্যাকাউন্ট', not_connected: 'সংযুক্ত নয়',
  about_title: 'আমাদের সম্পর্কে', about_hero_desc: 'উদ্ভাবনী ডিজিটাল সমাধানের মাধ্যমে ব্যবসা রূপান্তর করতে প্রতিশ্রুতিবদ্ধ।',
  our_story: 'আমাদের গল্প', story_p1: 'THRYLOS Tech একটি ছোট স্টার্টআপ থেকে বিশ্বস্ত প্রযুক্তি অংশীদার হয়ে উঠেছে।',
  story_p2: 'প্রযুক্তি ক্ষমতায়ন করা উচিত, জটিল করা নয়।', story_p3: '50+ প্রকল্প সফলভাবে সম্পন্ন।',
  years_excellence: 'উৎকর্ষের বছর',
  our_values: 'আমাদের মূল্যবোধ', values_desc: 'যে নীতিগুলি আমাদের সব কাজকে পথ দেখায়',
  innovation: 'উদ্ভাবন', innovation_desc: 'অত্যাধুনিক সমাধান।',
  excellence: 'উৎকর্ষ', excellence_desc: 'প্রতিটি প্রকল্পে পরিপূর্ণতা।',
  collaboration: 'সহযোগিতা', collaboration_desc: 'ক্লায়েন্টদের সাথে ঘনিষ্ঠভাবে কাজ।',
  integrity: 'সততা', integrity_desc: 'স্বচ্ছতা এবং সততা।',
  meet_team: 'আমাদের টিমের সাথে পরিচিত হন', team_desc: 'THRYLOS Tech-এর পিছনের প্রতিভাবান মানুষ', team_coming: 'টিম সদস্যরা শীঘ্রই আসছে...',
  services_hero_desc: 'ব্যবসায়িক বৃদ্ধি ত্বরান্বিত করতে ব্যাপক প্রযুক্তি সমাধান',
  no_services: 'এই মুহূর্তে কোনো সেবা উপলব্ধ নেই।',
  custom_solution: 'কাস্টম সমাধান', custom_solution_desc: 'আপনার প্রয়োজন অনুসারে সমাধান তৈরিতে বিশেষজ্ঞ।',
  request_quote: 'কোটেশনের অনুরোধ',
  get_in_touch: 'যোগাযোগ করুন', contact_hero_desc: 'প্রকল্প আছে? আমরা আপনার কাছ থেকে শুনতে চাই।',
  lets_connect: 'সংযুক্ত হন', connect_desc: 'যেকোনো প্রশ্ন হোক, আমরা সাহায্যের জন্য এখানে।',
  name: 'নাম', phone: 'ফোন', subject: 'বিষয়', message: 'বার্তা',
  your_name: 'আপনার নাম', your_email: 'your@email.com', phone_placeholder: '+91 XXX XXX XXXX',
  project_inquiry: 'প্রকল্প জিজ্ঞাসা', tell_us_project: 'আপনার প্রকল্প সম্পর্কে বলুন...',
  message_sent: 'বার্তা পাঠানো হয়েছে!', message_sent_desc: 'আমরা শীঘ্রই যোগাযোগ করব।',
  privacy_policy: 'গোপনীয়তা নীতি', terms_conditions: 'শর্তাবলী', payment_policy: 'পেমেন্ট নীতি', refund_policy: 'ফেরত নীতি',
  all_rights: 'সর্বস্বত্ব সংরক্ষিত।',
  faq_q1: 'একটি সাধারণ প্রকল্পে কত সময় লাগে?', faq_a1: 'সাধারণ ওয়েবসাইট ২-৪ সপ্তাহ, ফুল-স্ট্যাক অ্যাপ ২-৩ মাস।',
  faq_q2: 'আপনি কোন প্রযুক্তি ব্যবহার করেন?', faq_a2: 'React, Next.js, Node.js, Python, AWS ইত্যাদি।',
  faq_q3: 'লঞ্চের পর সহায়তা পাওয়া যায়?', faq_a3: 'হ্যাঁ! ৩০ দিনের বিনামূল্যে বাগ-ফিক্স সহায়তা।',
  faq_q4: 'পেমেন্ট কীভাবে কাজ করে?', faq_a4: 'মাইলস্টোন-ভিত্তিক পেমেন্ট। ৩০% অগ্রিম, ৪০% মাঝামাঝি, ৩০% ডেলিভারিতে।',
  faq_q5: 'ডেভেলপমেন্টের সময় অগ্রগতি দেখা যায়?', faq_a5: 'অবশ্যই! আপনি একটি ডেডিকেটেড ড্যাশবোর্ড পাবেন।',
  get_started_title: 'শুরু করুন', tell_about: 'নিজের সম্পর্কে এবং প্রকল্প সম্পর্কে বলুন',
  step_of: 'ধাপ', of: 'এর', personal_info: 'ব্যক্তিগত তথ্য', your_name_label: 'আপনার নাম', password: 'পাসওয়ার্ড',
  min_chars: 'ন্যূনতম ৬ অক্ষর', company_service: 'কোম্পানি ও সেবা', company_name: 'কোম্পানির নাম',
  your_company: 'আপনার কোম্পানি', service_interest: 'কোন সেবায় আগ্রহী?',
  project_details: 'প্রকল্প বিবরণ', describe_project: 'আপনার প্রকল্পের প্রয়োজনীয়তা বর্ণনা করুন...',
  back: 'পিছনে', continue_btn: 'চালিয়ে যান', creating_account: 'অ্যাকাউন্ট তৈরি হচ্ছে...', complete_setup: 'সেটআপ সম্পন্ন করুন',
  welcome_thrylos: 'THRYLOS-এ স্বাগতম!', account_created: 'আপনার অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে।',
  get_verified: 'যাচাইকৃত হন', choose_your: 'আপনার', plan: 'পরিকল্পনা বেছে নিন',
  plans_subtitle: 'যাচাইকৃত ব্যাজ দিয়ে আলাদা হন এবং প্রিমিয়াম সুবিধা আনলক করুন',
  plan_basic: 'বেসিক', plan_pro: 'প্রো', per_year: 'বছর', most_popular: 'সবচেয়ে জনপ্রিয়',
  feature_verified_badge: 'প্রোফাইলে যাচাইকৃত ব্যাজ', feature_profile_highlight: 'অনুসন্ধানে প্রোফাইল হাইলাইট',
  feature_priority_support: 'অগ্রাধিকার সহায়তা', feature_fast_delivery: 'দ্রুত প্রকল্প ডেলিভারি',
  feature_dedicated_pm: 'নিবেদিত প্রকল্প ব্যবস্থাপক', feature_priority_queue: 'অনুরোধের জন্য অগ্রাধিকার সারি',
  subscribe_now: 'এখনই সাবস্ক্রাইব করুন', already_subscribed: 'ইতিমধ্যে সাবস্ক্রাইব',
  already_subscribed_desc: 'আপনার ইতিমধ্যে একটি সক্রিয় যাচাই সাবস্ক্রিপশন আছে।',
  why_get_verified: 'কেন যাচাইকৃত হবেন?',
  trust_credibility: 'বিশ্বাস ও বিশ্বাসযোগ্যতা', trust_desc: 'যাচাইকৃত ব্যাজ বিশ্বাস তৈরি করে',
  fast_delivery_plan_desc: 'প্রো প্ল্যান ব্যবহারকারীরা অগ্রাধিকার ডেলিভারি পান',
  stand_out: 'আলাদা হন', stand_out_desc: 'অনুসন্ধান ফলাফলে প্রোফাইল হাইলাইট',
  priority_support_desc: 'সহায়তা টিম থেকে দ্রুত প্রতিক্রিয়া',
  find_people: 'লোক খুঁজুন', my_contacts: 'আমার পরিচিতি', my_profile: 'আমার প্রোফাইল',
  search_users: 'ব্যবহারকারী খুঁজুন', followers: 'অনুসারী', following: 'অনুসরণ করছেন', follow: 'অনুসরণ', unfollow: 'আনফলো',
  projects: 'প্রকল্প', no_reviews: 'এখনো কোনো পর্যালোচনা নেই', edit_profile: 'প্রোফাইল সম্পাদনা', view_plans: 'প্ল্যান দেখুন',
  starting_at: 'থেকে শুরু', contact_shared: 'যোগাযোগ শেয়ার', request_pending: 'অনুরোধ অপেক্ষমান', get_contact: 'যোগাযোগ পান',
  cta_desc: 'আসুন আলোচনা করি THRYLOS Tech কীভাবে আপনার ব্যবসা রূপান্তর করতে পারে।',
  write_review: 'পর্যালোচনা লিখুন',
};

const translations: Record<Language, Record<string, string>> = { en, hi, mr, gu, bn };

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLang] = useState<Language>(() => {
    return (localStorage.getItem('thrylos_language') as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLang(lang);
    localStorage.setItem('thrylos_language', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const languageLabels: Record<Language, string> = {
  en: 'English',
  hi: 'हिंदी',
  mr: 'मराठी',
  gu: 'ગુજરાતી',
  bn: 'বাংলা',
};
